### ISSUE TITLE
Pinout

### ISSUE THREAD

**Issue by WimDhont** [flyingflo/logamatic#4]
Hi there,

I was very happy to see this topic on a Logamatic 4000.
I had a NodeMCU and bought a MCP2515 CAN controller.
What I am missing is the pin / connection scheme between the NodeMCU and the MCP2515 CAN controller. 
Can you tell were I can find this?

Linked to Home Assistant, it should be possible to control your heating, correct?

Thanks for your response!

Regards,

Wim.

**Comment by flyingflo** [comment]
Sorry for not responding. You need to connect it to the SPI bus, don't remember exactly, but that is nothing special.
